// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/Categoria/Create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categorias"
                ],
                "summary": "Create a categoria",
                "parameters": [
                    {
                        "description": "Categoria data",
                        "name": "categoria",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Categoria"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.Body-types_Categoria"
                        }
                    }
                }
            }
        },
        "/Categoria/DeleteByID/{id}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categorias"
                ],
                "summary": "Delete a categoria by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "categoria ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.Body-string"
                        }
                    }
                }
            }
        },
        "/Categoria/GetAll": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categorias"
                ],
                "summary": "Get categorias",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.Body-array_types_Categoria"
                        }
                    }
                }
            }
        },
        "/Categoria/GetByID/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categorias"
                ],
                "summary": "Get categorias",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Categoria ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.Body-types_Categoria"
                        }
                    }
                }
            }
        },
        "/FormaPago/Create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FormaPago"
                ],
                "summary": "Create a FormaPago",
                "parameters": [
                    {
                        "description": "FormaPago data",
                        "name": "FormaPago",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.FormaPago"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.Body-types_FormaPago"
                        }
                    }
                }
            }
        },
        "/FormaPago/DeleteByID/{id}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FormaPago"
                ],
                "summary": "Delete a FormaPago by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "FormaPago ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.Body-string"
                        }
                    }
                }
            }
        },
        "/FormaPago/GetAll": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FormaPago"
                ],
                "summary": "Get FormaPago",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.Body-array_types_FormaPago"
                        }
                    }
                }
            }
        },
        "/FormaPago/GetByID/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FormaPago"
                ],
                "summary": "Get FormaPago",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "FormaPago ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.Body-types_FormaPago"
                        }
                    }
                }
            }
        },
        "/Product/Create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Create a new product",
                "parameters": [
                    {
                        "description": "Product data",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Producto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.Body-types_Producto"
                        }
                    }
                }
            }
        },
        "/Product/DeleteByID/{id}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Delete a product by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.Body-string"
                        }
                    }
                }
            }
        },
        "/Product/GetAll": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Get all products",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.Body-array_types_Producto"
                        }
                    }
                }
            }
        },
        "/Product/GetByID/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Get a product by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.Body-types_Producto"
                        }
                    }
                }
            }
        },
        "/Product/Update/{id}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Update a product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Product data",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Producto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.Body-types_Producto"
                        }
                    }
                }
            }
        },
        "/ProductComp/Create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Create a new productComp",
                "parameters": [
                    {
                        "description": "Product data",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.ProductoCompuesto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.Body-types_ProductoCompuesto"
                        }
                    }
                }
            }
        },
        "/ProductComp/DeleteByID/{id}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Delete a productComp by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.Body-string"
                        }
                    }
                }
            }
        },
        "/ProductComp/GetAll": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Get all products",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.Body-array_types_ProductoCompuesto"
                        }
                    }
                }
            }
        },
        "/ProductComp/GetByID/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Get a product by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.Body-dto_ProductoComp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.ProductoComp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "producto_compuesto": {
                    "$ref": "#/definitions/types.Producto"
                },
                "producto_principal": {
                    "$ref": "#/definitions/types.Producto"
                }
            }
        },
        "pkg.Body-array_types_Categoria": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Categoria"
                    }
                }
            }
        },
        "pkg.Body-array_types_FormaPago": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.FormaPago"
                    }
                }
            }
        },
        "pkg.Body-array_types_Producto": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Producto"
                    }
                }
            }
        },
        "pkg.Body-array_types_ProductoCompuesto": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.ProductoCompuesto"
                    }
                }
            }
        },
        "pkg.Body-dto_ProductoComp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.ProductoComp"
                }
            }
        },
        "pkg.Body-string": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                }
            }
        },
        "pkg.Body-types_Categoria": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.Categoria"
                }
            }
        },
        "pkg.Body-types_FormaPago": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.FormaPago"
                }
            }
        },
        "pkg.Body-types_Producto": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.Producto"
                }
            }
        },
        "pkg.Body-types_ProductoCompuesto": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.ProductoCompuesto"
                }
            }
        },
        "types.Categoria": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "nombre": {
                    "type": "string"
                }
            }
        },
        "types.FormaPago": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "nombre": {
                    "type": "string"
                }
            }
        },
        "types.Producto": {
            "type": "object",
            "properties": {
                "categoriaID": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "imagen": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string"
                },
                "precio": {
                    "type": "number"
                },
                "stock": {
                    "type": "boolean"
                }
            }
        },
        "types.ProductoCompuesto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "productoComponenteID": {
                    "type": "integer"
                },
                "productoPrincipalID": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
