definitions:
  dto.ProductoComp:
    properties:
      id:
        type: integer
      productoComponenteID:
        type: integer
      productoPrincipalID:
        type: integer
    type: object
  pkg.Body-array_types_Categoria:
    properties:
      data:
        items:
          $ref: '#/definitions/types.Categoria'
        type: array
    type: object
  pkg.Body-array_types_FormaPago:
    properties:
      data:
        items:
          $ref: '#/definitions/types.FormaPago'
        type: array
    type: object
  pkg.Body-array_types_Producto:
    properties:
      data:
        items:
          $ref: '#/definitions/types.Producto'
        type: array
    type: object
  pkg.Body-array_types_ProductoCompuesto:
    properties:
      data:
        items:
          $ref: '#/definitions/types.ProductoCompuesto'
        type: array
    type: object
  pkg.Body-array_types_Sucursal:
    properties:
      data:
        items:
          $ref: '#/definitions/types.Sucursal'
        type: array
    type: object
  pkg.Body-dto_ProductoComp:
    properties:
      data:
        $ref: '#/definitions/dto.ProductoComp'
    type: object
  pkg.Body-string:
    properties:
      data:
        type: string
    type: object
  pkg.Body-types_Categoria:
    properties:
      data:
        $ref: '#/definitions/types.Categoria'
    type: object
  pkg.Body-types_FormaPago:
    properties:
      data:
        $ref: '#/definitions/types.FormaPago'
    type: object
  pkg.Body-types_Producto:
    properties:
      data:
        $ref: '#/definitions/types.Producto'
    type: object
  pkg.Body-types_ProductoCompuesto:
    properties:
      data:
        $ref: '#/definitions/types.ProductoCompuesto'
    type: object
  pkg.Body-types_Sucursal:
    properties:
      data:
        $ref: '#/definitions/types.Sucursal'
    type: object
  types.Categoria:
    properties:
      id:
        type: integer
      nombre:
        type: string
    type: object
  types.FormaPago:
    properties:
      id:
        type: integer
      nombre:
        type: string
    type: object
  types.Producto:
    properties:
      categoriaID:
        type: integer
      id:
        type: integer
      imagen:
        type: string
      nombre:
        type: string
      precio:
        type: number
      stock:
        type: boolean
    type: object
  types.ProductoCompuesto:
    properties:
      id:
        type: integer
      productoComponente:
        $ref: '#/definitions/types.Producto'
      productoComponenteID:
        type: integer
      productoPrincipal:
        $ref: '#/definitions/types.Producto'
      productoPrincipalID:
        type: integer
    type: object
  types.Sucursal:
    properties:
      activo:
        type: boolean
      direccion:
        type: string
      id:
        type: integer
      nombre:
        type: string
      telefono:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/Categoria/Create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Categoria data
        in: body
        name: categoria
        required: true
        schema:
          $ref: '#/definitions/types.Categoria'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Body-types_Categoria'
      summary: Create a categoria
      tags:
      - categorias
  /api/Categoria/DeleteByID/{id}:
    post:
      consumes:
      - application/json
      parameters:
      - description: categoria ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Body-string'
      summary: Delete a categoria by ID
      tags:
      - categorias
  /api/Categoria/GetAll:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Body-array_types_Categoria'
      summary: Get categorias
      tags:
      - categorias
  /api/Categoria/GetByID/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Categoria ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Body-types_Categoria'
      summary: Get categorias
      tags:
      - categorias
  /api/FormaPago/Create:
    post:
      consumes:
      - application/json
      parameters:
      - description: FormaPago data
        in: body
        name: FormaPago
        required: true
        schema:
          $ref: '#/definitions/types.FormaPago'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Body-types_FormaPago'
      summary: Create a FormaPago
      tags:
      - FormaPago
  /api/FormaPago/DeleteByID/{id}:
    post:
      consumes:
      - application/json
      parameters:
      - description: FormaPago ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Body-string'
      summary: Delete a FormaPago by ID
      tags:
      - FormaPago
  /api/FormaPago/GetAll:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Body-array_types_FormaPago'
      summary: Get FormaPago
      tags:
      - FormaPago
  /api/FormaPago/GetByID/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: FormaPago ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Body-types_FormaPago'
      summary: Get FormaPago
      tags:
      - FormaPago
  /api/Product/Create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Product data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/types.Producto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Body-types_Producto'
      summary: Create a new product
      tags:
      - products
  /api/Product/DeleteByID/{id}:
    post:
      consumes:
      - application/json
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Body-string'
      summary: Delete a product by ID
      tags:
      - products
  /api/Product/GetAll:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Body-array_types_Producto'
      summary: Get all products
      tags:
      - products
  /api/Product/GetByID/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Body-types_Producto'
      summary: Get a product by ID
      tags:
      - products
  /api/Product/Update/{id}:
    post:
      consumes:
      - application/json
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Product data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/types.Producto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Body-types_Producto'
      summary: Update a product
      tags:
      - products
  /api/ProductComp/Create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Product data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/dto.ProductoComp'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Body-types_ProductoCompuesto'
      summary: Create a new productComp
      tags:
      - products
  /api/ProductComp/DeleteByID/{id}:
    post:
      consumes:
      - application/json
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Body-string'
      summary: Delete a productComp by ID
      tags:
      - products
  /api/ProductComp/GetAll:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Body-array_types_ProductoCompuesto'
      summary: Get all products
      tags:
      - products
  /api/ProductComp/GetByID/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Body-dto_ProductoComp'
      summary: Get a product by ID
      tags:
      - products
  /api/Sucursal/Create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Sucursal data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/types.Sucursal'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Body-types_Sucursal'
      summary: Create a new sucursal
      tags:
      - Sucursal
  /api/Sucursal/DeleteByID/{id}:
    post:
      consumes:
      - application/json
      parameters:
      - description: Sucursal ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Body-string'
      summary: Delete a sucursal by ID
      tags:
      - Sucursal
  /api/Sucursal/GetAll:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Body-array_types_Sucursal'
      summary: Get all Sucursales
      tags:
      - Sucursal
  /api/Sucursal/GetByID/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Sucursal ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Body-types_Sucursal'
      summary: Get a sucursal by ID
      tags:
      - Sucursal
  /api/Sucursal/Update/{id}:
    post:
      consumes:
      - application/json
      parameters:
      - description: Sucursal ID
        in: path
        name: id
        required: true
        type: integer
      - description: Sucursal data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/types.Sucursal'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Body-types_Sucursal'
      summary: Update a sucursal
      tags:
      - Sucursal
swagger: "2.0"
